### PR TITLE
Change clear_cache function implementation

### LINKED ISSUE #19: Use `wpdb` to remove all Head Tags transients
Currently, an option is being used to store the name of all transients. The list of transient names could be huge and this doesn't scale well. We should use `wpdb` to remove the transients based on a prefix instead of store all the names.

### PR DESCRIPTION
**Pull request by DAreRodz**
Fixes #19

### CODE REVIEW

**Comment by DAreRodz** [comment]
1. Gotcha!
2. Yeah, I know, I'm using a pattern in the mysql query that matches the timeouts too. 👍
3. I changed it to a static function because it's called by `uninstall`, that it's static too. Also, it's not using any instance variable so it doesn't make sense to make it a class method. 😊

**Comment by DAreRodz** [comment]
Yes, of course!

**Comment by DAreRodz** [comment]
The problem was the [WP Object Cache](https://developer.wordpress.org/reference/classes/wp_object_cache/). It caches every object that comes from the database. I was looking for a simple way to remove only the head tags transients, or almost just the `options` cache, but eventually I decided to use the [`flush`](https://developer.wordpress.org/reference/classes/wp_object_cache/flush/) method because I was receiving weird errors (like _Notice: Indirect modification of overloaded property has no effect_).

The `flush` method clears the entire object cache. I think it's not a problem, anyway.

**Comment by DAreRodz** [comment]
I'm gonna merge this PR as the tests are passing.

**Comment by luisherranz** [comment]
I don't think that is acceptable. Imagine flushing the whole object cache for a site with 100000 posts.

I've been checking the `delete_transient` function from WordPress and it looks like it takes care of the object cache: https://developer.wordpress.org/reference/functions/delete_transient/

Why not instead of a DELETE doing a SELECT and then using `delete_transient`?

The plugin Transients Manager seems to do it that way: https://github.com/pippinsplugins/Transients-Manager/blob/master/transients-manager.php

What do you think? Could it be possible?

**Comment by luisherranz** [comment]
> I'm gonna merge this PR as the tests are passing.

Why did you do that??

**Comment by DAreRodz** [comment]
> Why did you do that??

Sorry! 🙈

I thought it was _acceptable_ because the object cache lives just during the php request execution and that function is meant to be run when the AJAX hook is executed...

**Comment by DAreRodz** [comment]
Is that bad to do a flush?

**Comment by DAreRodz** [comment]
> Why not instead of a DELETE doing a SELECT and then using delete_transient?

We could do that, but what is the advantage of doing that instead of using an option as we did before?

**Comment by DAreRodz** [comment]
No problem. We can just open another PR to solve this, right? 😅

**Comment by luisherranz** [comment]
Yeah, no problem, but please don't merge without at least one approval (if it is not an exceptional situation). 

> I thought it was acceptable because the object cache lives just during the php request execution and that function is meant to be run when the AJAX hook is executed...

I didn't know that... [I've investigated a bit more](https://wp-rocket.me/blog/object-caching-use-wordpress/) and it turns out that object cache can persist more than one page load if you use memcached or redis. Big WordPress hostings always use one or the other so we can assume that is the case.

I reckon that flushing the object cache is probably not that drastic because I guess that it will get flushed each time you write to the database... so let's leave it like that.

**Comment by luisherranz** [comment]
Well... the wp-cli doesn't recommend to flush the object cache in production sites, so let's do this right:

> Beware of the performance impact when flushing the object cache in production.

https://developer.wordpress.org/cli/commands/cache/flush/

**Comment by luisherranz** [comment]
Can you open another PR?

**Comment by DAreRodz** [comment]
Yeah, sure!

**Pull request merged**
